# Generated by Django 4.1.7 on 2023-03-11 23:36

import commentary.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commentary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(
                validators=[commentary.validators.validate_min_comment_length]
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="text",
            field=models.TextField(
                validators=[commentary.validators.validate_min_post_length]
            ),
        ),
    ]
