# Generated by Django 4.1.7 on 2023-04-02 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_rename_original_title_book_full_title'),
        ('commentary', '0002_alter_comment_text_alter_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='verse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bible.verse'),
        ),
    ]
