# Generated by Django 4.1.7 on 2023-03-11 08:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dob",
                    models.DateField(
                        blank=True, validators=[profiles.validators.validate_dob]
                    ),
                ),
                (
                    "faith_tradition",
                    models.CharField(
                        choices=[
                            ("BAPT", "Baptist"),
                            ("PENT", "Pentecostal"),
                            ("AGN", "Agnostic"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: 05999999999",
                                regex="^(05)\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
