# Generated by Django 4.1.7 on 2023-03-26 15:21

import django.core.validators
from django.db import migrations, models
import profiles.validators


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True, validators=[profiles.validators.validate_dob], verbose_name='Birthdate'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='faith_tradition',
            field=models.CharField(choices=[('BAPT', 'Baptist'), ('PENT', 'Pentecostal'), ('AGN', 'Agnostic')], max_length=10, verbose_name='Faith Tradition'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=60, null=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 05999999999', regex='^(05)\\d{9}$')], verbose_name='Phone Number'),
        ),
    ]
