# Generated by Django 4.1.7 on 2023-03-22 13:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('symbol', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('number', models.IntegerField(unique=True)),
                ('original_title', models.CharField(max_length=15, unique=True)),
                ('testament', models.CharField(choices=[('old', 'Old Testament'), ('new', 'New Testament')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('number', models.IntegerField(validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.book')),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('number', models.IntegerField(validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)])),
                ('original_text', models.CharField(max_length=500)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.chapter')),
            ],
        ),
    ]
