# Generated by Django 4.1.7 on 2023-03-01 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='original_lang_id',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='testament',
            name='original_lang_id',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='verse',
            name='original_lang_id',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
