# Generated by Django 4.1.7 on 2023-03-22 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='original_title',
            new_name='full_title',
        ),
    ]
